#!/bin/bash

exec < /dev/tty

getJiraId ()
{
  local branchName=`git rev-parse --abbrev-ref HEAD`;
  echo `echo ${branchName} | grep -Eo "[A-Z]+-[0-9]+"`;
}

jiraId=`getJiraId`

message=`cat $1`

if [[ -z ${jiraId} ]]; then
 echo "No JIRA ID was found in the commit message";
 echo;
 echo "New issue will be created";
 jirosso create-issue --rename-branch;
 jiraId=`getJiraId`

 echo "$jiraId -- $message" > $1
fi

isAmend=`ps -ocommand= -p $PPID | grep -e '--amend'`;

if [[ ! -z ${isAmend} ]]; then
  message="${message} amended";
fi

jirosso commit-time --issue-num ${jiraId} --message "${message}";
