#!/bin/bash

exec < /dev/tty

branchName=`git rev-parse --abbrev-ref HEAD`;
jiraId=`echo ${branchName} | grep -Eo "[A-Z]+-[0-9]+"`;

message="`cat $1`"

if [[ -z ${jiraId} ]]; then
 echo "No JIRA ID was found in the commit message";
 echo;
 echo "New issue will be created";
 jiraId=`jirosso create_issue --message=${message}`;
 git branch -m ${branchName} ${jiraId}
fi

isAmend=`ps -ocommand= -p $PPID | grep -e '--amend'`;

if [[ ! -z ${isAmend} ]]; then
  message="${message} amended";
fi

jirosso commit-time --issue-num ${jiraId} --message ${message};
